### ISSUE TITLE
WPS on Spanish

### ISSUE THREAD

**Issue by sergioad** [wps-community/wps_i18n#241]
Hello when will be ready the Spanish translation for WPS office? I want see it complete if you can upload a spanish langpack package on AUR for Arch Linux?

**Comment by javierde22** [comment]
Hi, I am a Spanish programmer. Can I help to us doing a ES_es or CA_es translations?

How it works?

**Comment by alexwender1** [comment]
Look!
https://github.com/wps-community/wps_i18n/issues/400
