### ISSUE TITLE
wps can't open any file/directory turkish name include "şüğöçİı" letters.

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [wps-community/wps_i18n#316]
By the way I have started localizations for wps.

**Comment by ayhanyalcinsoy** [comment]
By the way I have started localizations for wps.

**Comment by wps-community** [comment]
On 04/01/2015 02:59 AM, Ayhan YALÇINSOY wrote:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wps-community/wps_i18n/issues/316>.
>

It works on my system with locale of en_US.

Could you please provide more details?
-- 
Regards
GOOGLE BEFORE ASKING

**Comment by ayhanyalcinsoy** [comment]
When I open this file "/home/PisiLinux/Masaüstü/Dropbox/yayınlarım/işgören sessizliği ve örgütsel bağlılık ilişkisi_tekstil sektöründe bir uygulama.doc", Wps shows  "/home/PisiLinux/Masast/Dropbox/yaynlarm/igren sessizlii ve rgtsel ballk ilikisi_tekstil sektrnde bir uygulama.doc Not a valid file"

**Comment by Armstrong1992** [comment]
@ayhanyalcinsoy No problem with it on my Os (Fedora 22, pl_PL.utf8), what Linux distro?

**Comment by ayhanyalcinsoy** [comment]
It is fixed in version 9.1.0.4953.
