### ISSUE TITLE
TR translate issue

### ISSUE THREAD

**Issue by Hakanseven12** [wps-community/wps_i18n#355]
When I create new spreadshets document I getting this error:

└──>>et<br />terminating with uncaught exception of type ks_exception
/usr/sbin/et: row 38:  5233 canceled 
 ${gInstallPath}/office6/${gApp} ${gOptExt} ${gOpt} "$@"

**Comment by chenjiexin** [comment]
what's the version you use?

**Comment by Hakanseven12** [comment]
Latest. When I trying in english language it is ok but when I try in turkish language its giving this error

**Comment by Hakanseven12** [comment]
Can you update turkish files again? This maybe fix the problem

**Comment by Hakanseven12** [comment]
we are fix this issue. I will send the update.
