### ISSUE TITLE
Interface Translation

### ISSUE THREAD

**Issue by alexwender1** [wps-community/wps_i18n#398]
Is this where the WPS Office translation is done? Are the translations being made elsewhere?

It was released the 2019 version - yesterday - for Linux. And there is no way to use the application in any language other than English / Chinese.

**Comment by Black-Flake** [comment]
Hi, I want create cs_CZ tranlastion.
what tools do I need?

**Comment by alexwender1** [comment]
This developer maintains the multi language WPS in Snapcraft. It extracts the language pack from the Windows version to Linux.

https://github.com/HoLuLuLu/wps-office-multilang

As the package is from the previous version... some terms in WPS 2019 are not translated. But about 70/80% is already complete.

I believe he will upgrade these packages in the coming days to the 2019 version.

**Comment by javierde22** [comment]
Hi, I am a Spanish programmer. Can I help us doing a ES_es or CA_es translations?

How it works?
